
Vagrant.configure("2") do |config|
  config.vm.define "marik1" do |marik1|
   node1.vm.box = "centos/7" 
   node1.vm.network "forwarded_port", guest: 80, host: 8081
   node1.vm.network "private_network", ip: "192.168.1.10"
end
  
config.vm.define "marik2" do |marik2|
  node2.vm.box = "centos/7"
  node2.vm.network "forwarded_port", guest: 80, host: 8082
  node2.vm.network "private_network", ip: "192.168.1.11"

end

end
