version: '3.0'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reshetun
    ports:
      - 3308:3306
  apache:
     image: bitnami/apache:latest
     restart: always
     ports:
       - 80:8080
     links:
       - mysql 

